name: 🚀 Fetch Data
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: 📂 Fetch API
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://fake-movie-database-api.herokuapp.com/api?s=batman'
        file: ${{ NOW }}.json
    - name: Commit File
      uses: EndBug/add-and-commit@v7
