name: 🚀 Fetch Data

on:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      uses: 1466587594/get-current-time@v2
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+08:00"
        
    - uses: actions/checkout@v2
    
    - name: 📂 Fetch data
      uses: ./fetch-api-data-action
      with:
        url: 'https://jsonplaceholder.typicode.com/todos/1'
        file: "${{ steps.current-time.outputs.time }}.json"
      
    - name: Commit File
      uses: EndBug/add-and-commit@v7
