name: 🚀 Fetch Data
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 📂 Fetch API
      uses: gautemo/fetch-api-data-action@1.0.2
      with:
        url: 'https://fake-movie-database-api.herokuapp.com/api?s=batman'
        file: 'testfile.json'
    - name: list files
      run: ls
